on:
  push:
    branches:
      - main
    paths:
      - "**.csv"
  workflow_dispatch:

jobs:
  create_raid_list_json:
    name: Create the raid list json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          repository: Matrix4348/matrix4348.github.io
          path: io
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Finally run the Python file
        run: python main/.github/scripts/create_raid_list.py
      - name: Commit changes
        run: |
          cd ./main/
          git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
          git config --global user.name "Workflow"
          git remote set-url origin https://x-access-token:GITHUB_TOKEN@github.com/${{ github.repository }}
          git add ./"community-gathered data"/raid_list.json
          git commit --allow-empty -m "Magically create raid_list.json"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_raid_list_json_to_github_io:
    name: Add the raid list json to github.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          repository: Matrix4348/matrix4348.github.io
          path: io
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Finally run the Python file
        run: python main/.github/scripts/create_raid_list.py
      - name: Commit changes
        run: |
          cd ./io/
          git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
          git config --global user.name "Workflow"
          git remote set-url origin https://x-access-token:GITHUB_TOKEN@github.com/Matrix4348/matrix4348.github.io.git
          git add raid_list.json
          git commit --allow-empty -m "Teleport raid_list.json to another world"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
