on:
  workflow_dispatch:

jobs:
  upload_raid_list_json_to_Filestack:
    name: Upload raid_list.json to Filestack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip requests
          python -m pip install filestack-python
      - name: Finally run the Python file
        env:
          app_secret: ${{ secrets.FILESTACK_APP_SECRET }}
          handle: ${{ vars.FILESTACK_FILE_HANDLE }}
        run: python .github/scripts/upload_raid_list_json_to_Filestack.py      
